import RPi.GPIO as GPIO
import time
GPIO.setmode(GPIO.BOARD)
"""Enables time and GPIOs"""
GPIO.setup(3,GPIO.OUT)
GPIO.setup(5,GPIO.OUT)
GPIO.setup(8,GPIO.OUT)
GPIO.setup(10,GPIO.OUT)
GPIO.setup(16,GPIO.OUT)
GPIO.setup(18,GPIO.OUT)
"""sets the GPIOs""" 
forward=GPIO.output (16,True)
        GPIO.output (18,True)
        GPIO.output (10,True)
        GPIO.output (8,False)
        GPIO.output(3,True)
        GPIO.output(5,False)


forward
time.sleep(0.5)
GPIO.output(3,False)
GPIO.output(5,True)
time.sleep(0.5)
GPIO.output(3,True)
GPIO.output(5,False)
time.sleep(0.5)
GPIO.output(3,False)
GPIO.output(5,True)
time.sleep(0.5)
GPIO.output(8,True)
GPIO.output(10,False)
GPIO.output(3,True)
GPIO.output(5,False)
time.sleep(0.5)
GPIO.output(3,False)
GPIO.output(5,True)
time.sleep(0.5)
GPIO.output(3,True)
GPIO.output(5,False)
time.sleep(0.5)
GPIO.output(3,False)
GPIO.output(5,True)
time.sleep(0.5)
GPIO.output(10,True)
GPIO.output(8,False)
GPIO.output(3,True)
GPIO.output(5,False)
time.sleep(2.5)
GPIO.output(5,True)
GPIO.output(3,False)
time.sleep(4)
GPIO.cleanup()
